#bootstrap and build
before_script: "./script/bootstrap"
script: "./script/cibuild"

#environment
language: ruby
rvm:
  - 2.5.3

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

before_install:
  - gem update --system

branches:
  only:
    - gh-pages
    - /.*/

notifications:
  email: true

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: true
cache: bundler

